### ISSUE TITLE
ToDoList and MS OneDrive

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#1]
I’ve recently moved my TDL files from DropBox to MS OneDrive. When saving (Ctrl-S) a Task List to a folder on OneDrive I often (50% of the time) see the following error pop-up.
 
![image001](https://cloud.githubusercontent.com/assets/12944354/8664444/af70c4f4-2a1a-11e5-8955-303459895599.png)
 
I’m the only one modifying the Main.tdl file. It seems that OneDrive sets an attribute on the Main.tdl file after uploading it to the cloud and this causes TDL to believe someone else modified the file from another copy of TDL.
 
For now, I’ve just disabled timestamp checking in TDL, so I’m not impacted by this issue. Could just be a bug in OneDrive for all I know, but I thought I’ll report this potential issue anyway.
 
![image004](https://cloud.githubusercontent.com/assets/12944354/8664428/847b115a-2a1a-11e5-8b4c-1e8e189dfa5b.jpg)

 The following is a minor issue, but a space (“ “) is missing after the “.” In the message below. Should read “… outside of TodoList. Would …” instead of “… outside of TodoList.Would …”
 
![image005](https://cloud.githubusercontent.com/assets/12944354/8664423/78bdebf8-2a1a-11e5-9c6c-6a1449a3ce3e.png)

**Comment by TonyGravagno** [comment]
If this behaviour with OneDrive or any other cloud service is not a bug, but consistent with how things are expected to work, then I'll add this info to the wiki.

For now, I've already flagged this ticket with the new Wiki label. Please use that when appropriate even if just to draw attention to a ticket where better documentation might help.

**Comment by abstractspoon** [comment]
I need to investigate it further so that we can understand what OneDrive is doing to change the datestamp because I know for a fact that this is not an issue w DropBox.

However, adding a list 'Known issues' alongside each cloud service may be helpful.

**Comment by TonyGravagno** [comment]
Wiki [File Menu](https://github.com/abstractspoon/ToDoList_Wiki/wiki/FileMenu) page updated with this note under **Save Tasklist** :

> Note: :warning: When saving a tasklist to a remote server like OneDrive or DropBox,
> it's possible for a TimeStamp Change warning to display. See [this issue report](/abstractspoon/ToDoList_Issues/issues/1) for
> information about what causes this and how to avoid the warning.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#31
