### ISSUE TITLE
TDL 70RC3 Reccurrence

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#13]
1) "Completed date" edit field still have problems.
In completed edit field, it is not possible to change the date without using drop-calendar.
In date edit fields, it is possible to change dates using keyboard arrows.
The procedure is to check the checkbox, then click on a part of the date, then use arrows to change the value.
- First problem, "as soon as you check, history is generated.
- Second problem, the first change of date with arrow generate more history, and it loose focus after that.

2) The Due date of new task do not respect the "Calculate next occurrence" option when set to "use completion date".
It use dotay's date to compute next occurrence.

**Comment by abstractspoon** [comment]
>> 2)

Can you add an image of the recurrence setup you used to show this bug, and tell me me what result you got that you think is wrong? Thx

**Comment by PatriceTorchet** [comment]
simple task list:
http://www.screencast.com/t/h6AWp9kbXv

Reccurrence setting: with 7 days
http://www.screencast.com/t/Sh0WU2VGb

Completed, the completed task is completed with the date I choose
bug 1:  the new task due date is today + 7 days, when I expect completion date + 7 days
http://www.screencast.com/t/rpbLHdT3IZo

bug 2: the new task look completed but is not (screen update artifact)
http://www.screencast.com/t/PP2w81KPFZnV

**Comment by abstractspoon** [comment]
Thx Patrice.

**Comment by abstractspoon** [comment]
Fixed in 7.0.RC4

Note: I've fixed the first problem by **always** popping up the calendar when the tick box is set, thus allowing the date to be modified before the task is recreated.

**Comment by PatriceTorchet** [comment]
Main problem solved, but the solution arise some secondary effects.

**Comment by TonyGravagno** [comment]
Please create new tickets for secondary effects or refer to them here. Use #00 to reference other issues. Thanks!
