### ISSUE TITLE
7.0 RC3 can't access Tasklist Attributes

### ISSUE THREAD

**Issue by DT996** [abstractspoon/ToDoList_Issues#14]
Get message "unsupported operation was attempted".

**Comment by Pierre-de-la-Verre** [comment]
Do you mean the standard-right-click on the columns of the attributes (Standard, user defined)? This is OK for me?

**Comment by DT996** [comment]
No...I'm talking about when in Preferences. In Preferences under User Interface>Tasklist Atributes if I left-click, I cannot change the preference because I get the message "unsupported operation was attempted".

**Comment by abstractspoon** [comment]
Hi Dave, this should be fixed in the 'new' RC3. If it is could you add a comment here and then 'close' the issue.

**Comment by DT996** [comment]
Dan,
I upgraded to the the new RC3 and the problem is now fixed.
