### ISSUE TITLE
Typo: Read-only

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#15]
Corrected typos on Read-only in all translation files.
found: Read-Only and Readonly

**Comment by abstractspoon** [comment]
Thx Patrice. I notice that there are now a duplicate for the line `"Read-only"	""	"text"` which can be removed in each file. Probably not a problem if left either.

**Comment by abstractspoon** [comment]
Hi Patrice. This should be fixed in the 'new' RC3. If it is could you add a comment here and 'close' the issue.

**Comment by PatriceTorchet** [comment]
Just removed duplited "Read-only" in translation files
