### ISSUE TITLE
Statistics / Burndown doesn't show Time/Date labels

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#16]
Compare v6.9
![150720163326_tmpimg](https://cloud.githubusercontent.com/assets/499473/8789978/2d45ae3a-2efd-11e5-9a54-abde222ef0c1.png)
with v7.0.RC2
![150720163352_tmpimg](https://cloud.githubusercontent.com/assets/499473/8789983/34675d1c-2efd-11e5-96eb-872115f48e55.png)

**Comment by abstractspoon** [comment]
This will need more investigation to determine the exact steps to reproduce this, because this is what I see:

![image](https://cloud.githubusercontent.com/assets/12944354/8827479/3877e10e-30d0-11e5-8e37-441a6a520bb8.png)

**Comment by TonyGravagno** [comment]
Seems to be fixed in 7.0RC3.2.

**Comment by abstractspoon** [comment]
ps. I'm not ruling out an issue because it uses some 3rd-party code that still needs work
