### ISSUE TITLE
Recurrence Dialog: Replace 'Recreate after...' options with 'Every ...' options

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#17]
Excerpt of discussion between dan.g and Patrice Torchet on [Code Project](http://www.codeproject.com/Messages/5094884/ToDoList-RC-Recurrence-dialog.aspx):

**Patrice Torchet**
> the Recreate new task offer a neat way to set a recurrence date to date, but only if the locked setting (date of completion) match my needs. If I want the same with Start Date or Due Date, it is not possible.

**dan.g**
> When I started looking closely at this question I finally realised why you asked me the question before "Isn't the 'Recreate...after' option just a duplication of 'Every... <time period>' combined with 'Recalc from ... completed date'"?

> And the answer would be "yes" if all the options had a simple 'Every ... <time period>' which they don't.

> My preference to resolving this would be to remove the 'Recreate...after' options and add simple 'Every ... <time period>' to weeks/months/years.

> Your thoughts?

**Patrice Torchet**
> Perfect for me. And this way, you don't have to grey the button. Should simplify things.

The plan therefore is to remove the 'Recreate after ... day(s)/week(s)/month(s)/year(s)' radio-buttons and insert a new 'Every ... week(s)/month(s)/year(s)' radio-button as the first item (for consistency with the 'Daily' radio-button of the same type which already exists.

Where people have existing tasks using the 'Recreate after day(s)/week(s)/month(s)/year(s)' options these will be converted in the equivalent 'Every ... day(s)/week(s)/month(s)/year(s)' option with the 'Recalculate ... from' option set to 'Completed'

**Comment by abstractspoon** [comment]
Should be fixed in RC4.

**Comment by PatriceTorchet** [comment]
This change is Ok for me.
