### ISSUE TITLE
Symantec quarantining Updates

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#19]
[Reported on CodeProject](http://www.codeproject.com/Messages/5094883/Re-ToDoList-RC.aspx) by WorkingNetwork.

[SONAR.SuspBeh!gen476](http://www.symantec.com/security_response/writeup.jsp?docid=2015-050111-4249-99)

Excerpt:

> I posted back in June against 7.0 RC1 that Symantec had flagged RC1 as having suspicious file download activity. For RC1 it quarantined the exe, the ini, and the tdl file I was working on, so I was able to recover.

> `Category: Quarantine
Date & Time,Risk,Activity,Status,Recommended Action,Path - Filename
23/06/2015 8:54:19 AM,High,todolist.exe (SONAR.SuspBeh!gen476) detected by SONAR,Quarantined,Resolved - No Action Required,c:\program files (x86)\todolist 7.0\todolist.exe`

> From Symantec's site;

> `SONAR.SuspBeh!gen476` is a heuristic detection that is designed to detect suspicious file downloads.

> It did the same for RC2, but had upped the severity and that time deleted the three files, exe, ini, and tdl. I had to recovery from backup!!!

> I suspect it is happening when you check for updates and update from within TDL. Symantec's SONAR heuristics is detecting that as suspicious download activity. I am downloading the new version from the forum and doing a fresh install, which seems to avoid Symantec deleting my tdl.

> The network guy where I'm working found he could whitelist TDL, but only for specific versions that Symantec knew about. Verison 7.0 appear to Symantec to have a verison of 6.9_9999, ie. not 7.0 but I think that is Dan's versioning for A/B/RC releases.

> So short answer for me was to fresh install new version, don't allow TDL to update.....and BACKUP your tdl!
 ....

> I have a suspicion that the visibility of the versions comes from the app/version being detected by the installed clients (ie. my PC) and reporting back to the Symantec Endpoint server (this is all Symantec ie. enterprise version of Norton's). Once the Symantec server knows about the app/version the Symantec administrator can then whitelist the app/version.

> I'm drawing this from the network guys where I work were telling me they could select a number of different versions of TDL but not the current version I had just installed. I think they could see versions that my PC had installed in the past. They always could see the previous version, but I was tending to install the new RC versions pretty quickly, so they had seen the new version before TDL did a update check (I have now disabled the update check on startup), and I think the update check, or updating TDL from the Help menu was triggering the SONAR exception.

> Today I did a fresh install of RC3 and had no issue.

**Comment by abstractspoon** [comment]
There is a related issue with MS's own SmartScreen technology which prevents the update getting downloaded at all.

**Comment by TonyGravagno** [comment]
From the SmartScreen for IE9 [FAQ](http://windows.microsoft.com/en-US/windows7/SmartScreen-Filter-frequently-asked-questions-IE9)

Q: One of the sites I visit is being flagged by SmartScreen Filter, but it's not an unsafe website. What can I do?

A: From the warning page, you can choose to report this site as a safe site. Click More information, and then click the Report that this site does not contain threats link to go online to the Microsoft feedback website, and then follow the instructions.

There is more current, though incomplete info at [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_SmartScreen)

**Comment by abstractspoon** [comment]
Thx Tony

I'm assigning this to you to put on the wiki. I've been looking at code signing as a way to help with SmartScreen but no luck finding anything reasonably priced as yet.

**Comment by TonyGravagno** [comment]
Added [new wiki page](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Installation-Issues) on the topic. Please close if this is acceptable.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#30
