### ISSUE TITLE
Support multiple file links in UDT $(selTFile) param

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#20]
This is a follow-on enhancement to new support for multiple files in file links.
Please support option to generate absolute paths from relative paths. Otherwise the UDT might need to know where the .tdl file is in order to generate that absolute path itself.

**Comment by abstractspoon** [comment]
Absolutely. The UDT should always be supplied the full file path.

**Comment by abstractspoon** [comment]
This is fixed in RC4.

**Comment by TonyGravagno** [comment]
The RC4 change breaks UDT definitions which insert the path before the file name. I was thinking about a new param like $(selTFileAll) that would return fullPath1" "fullPath2" "fullPath3" ...

**Comment by abstractspoon** [comment]
Can you give me a specific UDT example that RC4 breaks pls?

**Comment by TonyGravagno** [comment]
Honestly, I was looking at this and would have to contrive an example. I was thinking about a UDT that uses "$(folder)$(fileTitle)_Log.csv" where the folder and file name is separate. I'm happy with the full path for all file titles. Please close unless there is something else to be considered here. Thanks!

**Comment by abstractspoon** [comment]
This should stay open for '$(selTFileAll)' in 7.1

**Comment by TonyGravagno** [comment]
Removing OS, applies to all.

**Comment by abstractspoon** [comment]
Hi Tony. Can you move this to the Google Group as discussed last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support
