### ISSUE TITLE
TDL70RC4 Recurence dialog

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#22]
on Yearly tab, the anniversary options don't allow choosing the number of years.

**Comment by abstractspoon** [comment]
Hi Patrice. Can you move this to the Google Group as per my email last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support

**Comment by abstractspoon** [comment]
Moved to Google Group
