### ISSUE TITLE
"Show tasks due ..." - Refresh problem

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Issues#23]
Taken from posting
http://www.codeproject.com/Articles/5371/ToDoList-An-effective-and-flexible-way-to-keep-on?msg=5087018#xx5087018xx
xxx
At the moment my next task is due to 17th of July, also "End of next week".

If I ask for "Show tasks due to: today / tomorrow / this week", then I get the correct answer "no tasks dued ..."

But if I ask for "next week / this month / next month", then I get

- the correct answer for the first query (e.g. "1 task next week")
- and always the same (first) answer for the following queries with results: "this month: 1", "next month:1"
- BUT asking for "Today" I get the correct answer "none" again.

I have to restart to get
- the correct answer for the first query (e.g. "15 tasks next month")
- and again always the same (first) answer for the following queries: "this week: 15", "next week: 15"

So:
- queries with result "None" are correct
- queries with result "> 0" have a refreshing problem

**Comment by abstractspoon** [comment]
Peter, can you add screenshots or a screencast pls?

**Comment by abstractspoon** [comment]
Thx Peter, I can reproduce this.

**Comment by Pierre-de-la-Verre** [comment]
I made a screencast with your file to show the problem:

Link:
http://autode.sk/1KDfOSW 

Comment:
Feature "Show Task Due" is only correct for the first time, then it shows always the same result. If a query should show no results - that's correct and resets the data for one time.

After reopening the file it behaves in the same way.

Maybe a refreshing problem of the file in the background

**Comment by abstractspoon** [comment]
Sorry Peter. The problem was all at my end - I thought you were meaning the Due By **filter** which you clearly weren't!

**Comment by Pierre-de-la-Verre** [comment]
Fixed with TDL 7.0 RC5, 9. August 2015
