### ISSUE TITLE
Edit a file-link creates a new one

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Issues#24]
Example:
- I have a file-link: "c:\data\test.doc"
- Select the value in the edit field, and modify it to ""c:\data\projectX\test.doc"
- Press F8 for the next task

Result: you have two entries
- "c:\data\test.doc"
- "c:\data\projectX\test.doc"

Bug or feature?

**Comment by abstractspoon** [comment]
It has always been this way for all droplists.

It's always difficult to 'know' the user's intent in situations like this, and the alternative of deleting the 'original' has more significant consequences.

**Comment by TonyGravagno** [comment]
Removed labels as this is not W7-specific and it no longer needs discussion.
