### ISSUE TITLE
vertical offset between the both panels (split view)

### ISSUE THREAD

**Issue by Simplenuity** [abstractspoon/ToDoList_Issues#28]
In general: It can't be produced in a consistent way. The offset is quite variable between different sets of data. 

These ones is from a fresh install, without any config change. Just loading the Introduction.tdl:

Task Tree
![selection_006](https://cloud.githubusercontent.com/assets/13347943/9032249/be2bbd04-3a10-11e5-98e5-80cd76b2835f.png)

List View
![selection_009](https://cloud.githubusercontent.com/assets/13347943/9032828/b2027eea-3a16-11e5-9052-1abe91bbabed.png)

These ones are from my personal TDL file, the offset is quite big:

Task Tree
![selection_002](https://cloud.githubusercontent.com/assets/13347943/9032925/487d2942-3a17-11e5-9484-c337a84e5d09.png)

-----
![selection_003](https://cloud.githubusercontent.com/assets/13347943/9032243/add97626-3a10-11e5-9ea4-69ab15bcad60.png)
-----
List View
![selection_010](https://cloud.githubusercontent.com/assets/13347943/9032999/cb077138-3a17-11e5-9445-33ee10d208c9.png)

**Comment by Simplenuity** [comment]
fixed :)

**Comment by Simplenuity** [comment]
fixed :)

PS: sorry for closed-reopen-loop, was battling with GitHub

**Comment by abstractspoon** [comment]
I'm glad you won :D

Rgds, .dan.g.

www.abstractspoon.com

**Comment by Simplenuity** [comment]
Hi Dan,

Sorry, my testing was obviously not thorough enough. I forgot to test with filters active. With filters active in tree view I get an offset of one row. (TDL 7.0, Linux)
Shall I open a new issue or do you prefer to handle it via this ticket?

Still with limited internet access. Will upload screenshots and futher info if needed asap.

**Comment by TonyGravagno** [comment]
Reopening and assigning Dan.

**Comment by abstractspoon** [comment]
@Simplenuity : Can you reproduce this with the 'Introduction' tasklist and a default filter?

**Comment by Simplenuity** [comment]
Hi Dan,

I can reproduce it with the 'Introduction' tasklist, two additional task ticked as completed and the 'C) Completed Tasks' filter. It seems to have to do with vertical scrolling active/necessary at some stage of the process.
Here are steps to reproduce the behavior after starting from scratch:
TDL 7.0.1
Linux

**First example**
1- Start TDL with 'Introduction' tasklist:
Please notice small white bar on top of first task. Just in case, that's important for the overall trouble shooting.
![sample tasklist - todolist c abstractspoon_001](https://cloud.githubusercontent.com/assets/13347943/9627281/29409e12-51b7-11e5-948c-8f48f0685233.png)

2- Select two additional tasks as completed:
![sample tasklist - todolist c abstractspoon_002](https://cloud.githubusercontent.com/assets/13347943/9627346/a5f6094c-51b7-11e5-81d9-8a4b03fcf346.png)

3- Reduce hight of TDL window:
![sample tasklist - todolist c abstractspoon_008](https://cloud.githubusercontent.com/assets/13347943/9627598/3b349234-51b9-11e5-9d75-5792bfbd17c1.png)

4- Select Filter C) Completed Tasks:
Note the vertical offset!
![sample tasklist - todolist c abstractspoon_009](https://cloud.githubusercontent.com/assets/13347943/9627617/55472b0a-51b9-11e5-90c0-3791c41b70fb.png)


**Second example**
1- Start TDL with 'Introduction' tasklist:
![sample tasklist - todolist c abstractspoon_001](https://cloud.githubusercontent.com/assets/13347943/9627281/29409e12-51b7-11e5-948c-8f48f0685233.png)

2- Select two additional tasks as completed:
![sample tasklist - todolist c abstractspoon_002](https://cloud.githubusercontent.com/assets/13347943/9627346/a5f6094c-51b7-11e5-81d9-8a4b03fcf346.png)

3- Select Filter C) Completed Tasks:
Issue doesn't show up yet!
![sample tasklist - todolist c abstractspoon_003](https://cloud.githubusercontent.com/assets/13347943/9627376/d77d434a-51b7-11e5-8d66-4c728b9c1b9d.png)

4- Reduce hight of TDL window:
![sample tasklist - todolist c abstractspoon_004](https://cloud.githubusercontent.com/assets/13347943/9627393/0141728c-51b8-11e5-9e57-d1c5060ca0bb.png)

5- Select Filter A) All Tasks:
Note the vertical offset!
![sample tasklist - todolist c abstractspoon_005](https://cloud.githubusercontent.com/assets/13347943/9627415/22ba93b2-51b8-11e5-8f32-74cf060f1c7c.png)

Please let me know if you need further information/ testing. On the weekend I should have my system and full internet access.

Ryan

**Comment by Simplenuity** [comment]
moved over to GoogleGroups
