### ISSUE TITLE
Import tasks via clipboard: there is an empty line added on top of the list

### ISSUE THREAD

**Issue by Simplenuity** [abstractspoon/ToDoList_Issues#29]
It doesn't seem to influence the imports I performed/tested. However it's a bit confusing.
Maybe it has a purpose I haven't discovered yet?

![selection_007](https://cloud.githubusercontent.com/assets/13347943/9032402/63242246-3a12-11e5-9374-fdcddf81542a.png)

Clearing the clipboard and activating the Import Tasks... leads to the cursor sitting in the second line:

![import tasks_008](https://cloud.githubusercontent.com/assets/13347943/9032704/5fdc2d74-3a15-11e5-81b6-ba2547414fa8.png)

**Comment by abstractspoon** [comment]
The leading blank line is a hack to compensate for the fact that the csv importer expects the first line to be a header line so w/o a blank line the first line of data would be lost.

I'll have another think about it.

**Comment by abstractspoon** [comment]
I can confirm this to be an issue on all OSes so I've modified the labels appropriately

**Comment by abstractspoon** [comment]
This will required a checkbox to be added the CSV import dialog for the user to specify whether there is a column header line to be imported

**Comment by TonyGravagno** [comment]
Please assign to me when the UI has been updated so I can get the wiki.

**Comment by Simplenuity** [comment]
Dan, does this - "abstractspoon added this to the 7.1 Feature Release milestone" - mean, there is no need to move it over to GoogleGroups as you noted it down on your release plan?

**Comment by abstractspoon** [comment]
>> there is no need to move it over to GoogleGroups as you noted it down on
your release plan?

Unfortunately not. It's not yet in my tasklist... :)

Rgds, .dan.g.

www.abstractspoon.com

**Comment by Simplenuity** [comment]
OK, have moved it over as feature request :)

Ryan

**Comment by Simplenuity** [comment]
moved over to GoogleGroups
