### ISSUE TITLE
Improving file links

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#3]
_From @PatriceTorchet on July 13, 2015 23:14_

When using "directory" icon at end of "File Link" edit field to link to a file that is in same directory as TaskList, or in subdirectory, the file name is relative to TaskList.
When dropping the same file link from Windows Explorer, the file name is absolute.

Enhancement: make the file name relative to TaskList everytime it is possible

_Copied from original issue: abstractspoon/ToDoList_Wiki#10_

**Comment by abstractspoon** [comment]
I'm treating this as a consistency bug

**Comment by abstractspoon** [comment]
Hi Patrice 

Can you give me an example of a taklist path and an explorer file path that does not work because my simple tests seem to work correctly?

Thx

**Comment by TonyGravagno** [comment]
I'm also seeing that using File Open to pull in a file has the relative file path. But if a task list is opened by different people the path might be in a different location relative to each user. Some thought needs to be put into whether a link is relative or absolute. I think in all cases we should get the option to set how it's going to be assigned.

**Comment by PatriceTorchet** [comment]
Hi Tony,
There is no problem here
the case is that one have files in same directory or in subdirectory relative to TaskList, if you get the file link with TDL dialog, the link is
.\MyFile.pdf or .\subdir\MyFile.pdf which are both relative to TaskList directory.
If you drop the link from Explorer, the link become absolute
Z:\TaskDir\MyFile.pdf or Z:\TaskDir\subdir\MyFile.pdf
If a network user  is on W: absolute links are broken.

**Comment by TonyGravagno** [comment]
@PatriceTorchet, I understand your report, I'm adding to it because it's related. Dan says it's a consistency bug. I don't know if he's thinking about making links consistently absolute or consistently relative. I'm suggesting neither might be the right answer.

**Comment by abstractspoon** [comment]
@PatriceTorchet What exactly is the nature of your Z: drive? This may be affecting things?

**Comment by PatriceTorchet** [comment]
Hi Dan, the Z drive is only an example for a network drive that another user can call W drive.

**Comment by PatriceTorchet** [comment]
RC4 bug
My TaskList is at D:\Atelier , I just dropped a file link from a sub dir : OK
Then, I dropped a file link of a PDF that is in MyDocuments, the link is 
..\..\..\MyDocuments\FA1501-0157.pdf 
it should be absolute

**Comment by abstractspoon** [comment]
It sounds like you have been thinking of 'relative' to mean 'below' or 'subfolder'.

ie. '..\ ..\ ..\MyDocuments\FA1501-0157.pdf' is a relative path.
