### ISSUE TITLE
Synchronisation bug between in Task Tree between the Title and Attribute panes

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#30]
OS: Windows 7
TDL: 7.0.RC4

1. Create a clean install of TDL 7.0.RC4
2. Unzip [this file](https://github.com/abstractspoon/ToDoList_Issues/raw/master/Issues/Issue%2330.zip) into the root of that install folder
3. Run TDL
*Observe the incorrectly placed horizontal scrollbar in the Attributes pane*

4. Move the mouse cursor over the Title pane and use the mouse wheel to scroll down
*Observe that the Attributes pane does not scroll as the Title pane scrolls.*

![image](https://cloud.githubusercontent.com/assets/12944354/9051296/1758ceb8-3a9c-11e5-87e6-4c1dcd0fe3ba.png)

**Comment by Pierre-de-la-Verre** [comment]
Win 7 x64, Zoom 125%, Classic Theme:
I get no scrollbar under the Attr. - only a grey area. When I click this a area, "something" (e.g. the prio. color) blinks very, very shortly.
