### ISSUE TITLE
Updates for Help > Commandline Options

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#32]
1. The -g option is missing from the options. Suggested text : "Saves intermediate file from transform operations" (requires text in translation resources?). This feature and all others is now being documented in [wiki](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Command-Line)
1. ~~Please check the list to see if any other options are missing. (If anything is missing, please indicate it here so that the wiki can be updated.)~~
1. The Copy All button does not sort the options, where the displayed list is sorted. Please output the copied list in the same order as the displayed list.
1. Would help to have a link to the wiki page at the bottom of the page. "See _wiki_ for details"
1. The help text for -cm is "Sets the 'Comments' for the currently selected task". I recommend changing that to "Adds to Comments for the currently selected task". ( Is there a way to actually Set/Replace the comment rather than Appending to it?)
1. Is there an option to start a command line and leave TDL minimized, or close afterward? Or should this be done through a shell which closes the app when the command finishes executing?

**Comment by TonyGravagno** [comment]
Withdrawing request 2 as undocumented switches are considered internal for development purposes only.

**Comment by TonyGravagno** [comment]
Added request 5 about -cm.

**Comment by abstractspoon** [comment]
Hi Tony

I always welcome requests for clarification and in this case you are
correct that '-g' provides more than just classic logging which I had
forgotten about because I hardly use that feature myself.

So I am happy for you to include '-g' as it related to XSL debugging,
though I think I'd like to remain an invisible in-app feature for the time
being.

Rgds, .dan.g.

www.abstractspoon.com

**Comment by abstractspoon** [comment]
> 3.. Copy All not sorted

Will fix for release.

> 4.. Add wiki links to dialog

I'd rather figure out a scalable way to add a help icon button to all dialogs and direct each dialog to its corresponding wiki page. This would have the additional benefit of needing no text changes and can therefore be a 'rolling change' in 7.0.

> 5.. Explanation of -cm

Agree totally. An option to replace the comments would have to be a feature request in 7.1.

> 6.. Prevent TDL showing 

If there is an instance of TDL already running that can handle the commandline request then the instance just started is meant to close without being shown. Perhaps you could describe a specific situation where this is not happening?

**Comment by TonyGravagno** [comment]
On 2: If you're sure that all user-visible switches are in the help list then we'll leave that one closed. I just want to make sure implemented functionality is not left undocumented.

On 4: I really like the idea of a generic help button.

On 5: I'd like to see the text changed from Set to Add, but I don't have a use case for replacing all comments, so I won't add the request. Was just asking.

On 6: I'm just wondering if we can do a transparent/silent post into TDL without bringing it to the foreground. For example, someone might create a hook in Outlook where creating an appointment or sending an email updates a related task. There's no need to display the UI, no interaction is desired, TDL is just logging data. So I'm thinking about switches like -xm for eXecute and stay minimized, or -xx for eXecute and eXit.

**Comment by abstractspoon** [comment]
> On 6

ToDoList should already act silently under most conditions.It was designed, written and tested to do so, so there should be no additional need for a commandline flag.

Why don't you create a tasklist that uses the file link field to update another instance of TDL and see for yourself?

**Comment by abstractspoon** [comment]
Hi Tony. Can you move what's still outstanding to the Google Group as discussed last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support
