### ISSUE TITLE
Undo need 2 steps to cancel the completion of a recurring task

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#33]
TDL 70RC4 + TDL 6.9.6

Undo treat completion of recurring task with "Create a new task" as 2 steps
first Undo cancel the new task, the second Undo cancel Completion.

Should be a single step

**Comment by abstractspoon** [comment]
Hi Patrice. Can you move this to the Google Group as per my email last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support
