### ISSUE TITLE
Custom attr. with "Number (whole)" - wrong display

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Issues#34]
OS: Win 7 x64, German, Display 125% Classic Theme

TDL: 7.0 RC5

- Define a "Custom Task Attribute", data type "number (whole)"
- Enter a long number up to 10 digits, e.g. 1234567890
-> Everything OK, display in edit-filed and in column is OK

- Enter the next digit, e.g. 12345678901
-> Display in edit-filed is OK, display in column shows a negative value
![tdl_number_whole](https://cloud.githubusercontent.com/assets/13277944/9175846/00a363ae-3f88-11e5-886a-d3185c13e118.png)

**Comment by TonyGravagno** [comment]
@Pierre-de-la-Verre - It's OK to leave tasks unassigned. Dan reads everything and undoubted picks up code issues anyway. I read all issues just in case a wiki update is required. But thanks for using the Labels.

**Comment by Pierre-de-la-Verre** [comment]
Fixed with TDL 7.0, 15.08.2015
