### ISSUE TITLE
Custom task Attrib: Paste text into number-types

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Issues#35]
OS: Win 7 x64, German, Display 125% Classic Theme

TDL: 7.0 RC5

* Define a "Custom Task Attribute", data type "number (whole)"
* Try to type in "abc" - it is refused because it is no number: OK
* Define a "Custom Task Attribute", data type "number (fractional)"
* Try to type in "abc" - it is refused because it is no number: OK

Problem:
* Paste in a text from clipboard into both fields - both are accepted. although it is no number.
* Press F7 and F8 to go back and forward
* The edit fields show still the text, the columns show 0 and 0.00
![tdl_text_in_numbers](https://cloud.githubusercontent.com/assets/13277944/9176424/8d2903f8-3f8b-11e5-8469-c476c65543d2.png)

**Comment by abstractspoon** [comment]
Thx Peter.

This would also appear to be an issue with 'built-in' number fields (eg. Time Spent).

Can you confirm this? If so, could you modify the issue text to reflect this?

**Comment by Pierre-de-la-Verre** [comment]
Build-in number fileds (costs, time spent, time-estimated...) remove the pasted string and set both column and edit-field to 0 (zero).

**Comment by Pierre-de-la-Verre** [comment]
Fixed with TDL 7.0, 15.08.2015
