### ISSUE TITLE
Add switch to allow custom tray icon coloring

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#36]
[Ref](http://www.codeproject.com/Messages/5106054/Re-Can-we-change-the-tasklist-icon-per-instance.aspx) : It's helpful for tray icons for different configs or releases to be distinguishable. This can be implemented with a command-line switch.

I'd recommend "-ic" for Icon Color, as all other switches are 1-3 characters and not 4.
Example: -ic cFF0000 for a 'red' tag

**Comment by abstractspoon** [comment]
Hi Tony. Can you move this to the Google Group as discussed last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support
