### ISSUE TITLE
Tray icon is from v6, should be new v7 icon

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#37]
This was discussed in the forum. Personally I don't think the new icon is important as people just recognize TDL as TDL and the v7 branding isn't that important. Introducing a new icon just creates a need for yet another one later on.

But since the icon should be the new one for this release I'm logging this as a bug and the resolution is open to whatever Dan wants.

**Comment by PatriceTorchet** [comment]
works on release
