### ISSUE TITLE
Parent tasks not updated in grid per calcs when child edited

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#38]
When entering a number in the time spent field, we see in the grid the task is updated with each keypress. This is consistent with 6.9.x and 7.0RCx.

In 6.9 parent tasks are recalculated and repainted with each keystroke, while in 7.0RC5 the parent tasks are not repainted until focus is set on the grid (not just on the next edit field).

Discussion [here](http://www.codeproject.com/Messages/5108033/Behaviour-change-calc-field-isnt-changed-until-gri.aspx).

**Comment by abstractspoon** [comment]
Fixed in 7.0 Release?

**Comment by TonyGravagno** [comment]
Confirmed fixed
