### ISSUE TITLE
German special characters are not displayed correctly

### ISSUE THREAD

**Issue by Tiger-Wutz** [abstractspoon/ToDoList_Issues#39]
German special characters are not displayed correctly in the program. If the file "German (Germany) .csv" will be saved in ANSI format, they are displayed correctly. See also the two images as an attachment ... version 7.0.0.0

Nice program, keep it up

Tiger ![aikido](https://cloud.githubusercontent.com/assets/13817317/9292586/6fbacb2c-4403-11e5-9f98-9a7a59f17e20.gif)

![todo](https://cloud.githubusercontent.com/assets/13817317/9292575/ed6ad11c-4402-11e5-9aac-253c7eb39757.jpg)
![todo2](https://cloud.githubusercontent.com/assets/13817317/9292574/ed6abc72-4402-11e5-8987-9aafe1ee7cd0.jpg)

**Comment by Pierre-de-la-Verre** [comment]
Yes Tiger

 

you are right – there is wrong fileformat in the files. I saw that you could help yourself – Dan will fix the download package soon

 

Peter

 

Von: E.T. [mailto:notifications@github.com] 
Gesendet: Sonntag, 16. August 2015 10:43
An: abstractspoon/ToDoList_Issues
Betreff: [ToDoList_Issues] German special characters are not displayed correctly (#39)

 

German special characters are not displayed correctly in the program. If the file "German (Germany) .csv" will be saved in ANSI format, they are displayed correctly. See also the two images as an attachment ...

Nice program, keep it up

Tiger  <https://cloud.githubusercontent.com/assets/13817317/9292586/6fbacb2c-4403-11e5-9f98-9a7a59f17e20.gif> Das Bild wurde vom Absender entfernt. aikido

 <https://cloud.githubusercontent.com/assets/13817317/9292575/ed6ad11c-4402-11e5-9aac-253c7eb39757.jpg> Das Bild wurde vom Absender entfernt. todo
 <https://cloud.githubusercontent.com/assets/13817317/9292574/ed6abc72-4402-11e5-8987-9aafe1ee7cd0.jpg> Das Bild wurde vom Absender entfernt. todo2

**Comment by abstractspoon** [comment]
Peter

Somewhere in the process the encoding of some of the translation files was changed from 'UTF-8 with BOM' to 'UTF-8 without BOM' and thus TDL assumed the files were Ansi instead of UTF8.

I've corrected the files and the download package.

**Comment by Pierre-de-la-Verre** [comment]
Dan
this means that when I paste into Github I have to keep this "BOM  dot" and have to paste beginning with the "T"?

**Comment by abstractspoon** [comment]
The best thing probably would to leave the first line totally untouched.

Rgds, .dan.g.

www.abstractspoon.com

**Comment by Pierre-de-la-Verre** [comment]
Fixed with a new update package.
