### ISSUE TITLE
Add "lock feature" to date-values

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#4]
_From @Pierre-de-la-Verre on July 13, 2015 10:58_

To avoid erroneous modification (manually or with "Offset Task Dates"), dates should have a "lock feature / read-only-tag".

_Copied from original issue: abstractspoon/ToDoList_Wiki#9_

**Comment by Pierre-de-la-Verre** [comment]
Maybe in connection with
"Add ability to lock a "container only" parent task #40"
https://github.com/abstractspoon/ToDoList_Issues/issues/40

**Comment by abstractspoon** [comment]
Hi Peter. I know you've been away but can you move this to the Google Group as per my email last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support
