### ISSUE TITLE
Add ability to lock a "container only" parent task

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#40]
Some tasks are created for organization. They are merely containers or folders, and never go away. Please add the ability to lock a task so that its sub-tasks archive without closing the parent, while preserving the structures. So the container class would be present in both live and archive lists.

Example, top-level task "Enhancements" is just a container. But individual enhancements and related sub-tasks can be closed. The archive would have the Enhancements parent task and those tasks would be removed from the live list, but the Enhancements container itself would not be removed from the live list.

For tasks that are flagged as permanent containers like this, please disable the Closed check/flag and prevent the item from being closed.

Posted for @Citorix per request [here](http://www.codeproject.com/Messages/5109998/Tasks-that-server-only-as-folders.aspx).

**Comment by Pierre-de-la-Verre** [comment]
Maybe in connection with
" Add "lock feature" to date-values #4 "
https://github.com/abstractspoon/ToDoList_Issues/issues/4

**Comment by abstractspoon** [comment]
Hi Tony. Can you move this to the Google Group as discussed last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support
