### ISSUE TITLE
Artefacts in the dialogue "Select Task Icon" when changing the icon label

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Issues#41]
TDL 7.0
Win 7 x64, Classic Theme, 125 % Display

When changing the icon label the software displays "copies" of the edit field on the wrong place, depending on the size of the entire dialogue and the (non-)display of the first column

Screencast:
http://autode.sk/1PkQ7EV

**Comment by abstractspoon** [comment]
Does 6.9 display the same problem? ie. Is this regression or a new bug?

**Comment by abstractspoon** [comment]
Can you also embed a screenshot of just the dialog?

**Comment by Pierre-de-la-Verre** [comment]
It is also in 6.9.6 (fresh downloaded and started from scratch).
Here are two screenshots (small from 6.9.6; large from 7.0).

But priority is really low.
![tdl_7-0_select_task_icons-artefacts_6-9-6](https://cloud.githubusercontent.com/assets/13277944/9350529/f6aed60a-4651-11e5-8920-e6fda7f932c0.png)
![tdl_7-0_select_task_icons-artefacts_7-0](https://cloud.githubusercontent.com/assets/13277944/9350528/f6ae432a-4651-11e5-8545-8aa57a170d4e.png)

**Comment by abstractspoon** [comment]
Peter

Does the problem still occur if you first widen the dialog far enough to hide the horizontal scrollbar?

**Comment by Pierre-de-la-Verre** [comment]
The hiding of the horizontal scrollbar ensures that the first column is displayed, and this ensures that the problem does not occur. But it is not clear if the real background is based on the scrollbar or on the first column.

**Comment by abstractspoon** [comment]
Hi Peter. I know you've been away but can you move this to the Google Group as per my email last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support

**Comment by Pierre-de-la-Verre** [comment]
Moved to Google Groups:
https://groups.google.com/forum/#!category-topic/abstractspoon-todolist-support/bug-reports/zua-gix9fXs
