### ISSUE TITLE
Flag Attribute not working on old list

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#42]
TDL70
Win7 Pro 64
TDL70 installed from scratch

I sent to you the file.
The Flag columns attribute is not clickable or not active.

Working on new list

Checked on 2 computers

**Comment by Pierre-de-la-Verre** [comment]
On my system I can flag and unflag tasks in old and new lists. Maybe (I don't remember) the display of the current flag is finer than before and has a pale green color ...????

**Comment by abstractspoon** [comment]
I haven't received the file yet...

**Comment by abstractspoon** [comment]
@Pierre-de-la-Verre 
> has a pale green color

Can you attach a screenshot pls?

**Comment by PatriceTorchet** [comment]
just resent the file.

**Comment by PatriceTorchet** [comment]
To Pierre: not a color issue, Flag works with new list on same computer.
To Dan: Screenshoot will show nothing: the mouse arrow stay an arrow while moving over the Flag column. With new list, mouse arrow switch to "pointing finger" while over the column.

**Comment by Pierre-de-la-Verre** [comment]
Here is my screenshot. But it seem to be depending on the special file / special setting of Patrice.
![tdl_7-0_used_flags](https://cloud.githubusercontent.com/assets/13277944/9350422/2f6cb134-4651-11e5-8ca5-77624973f6d5.png)

**Comment by abstractspoon** [comment]
@PatriceTorchet This is what I see when I load the tasklist with a fresh install. After I check-out the tasklist the flag column works fine for me.

![image](https://cloud.githubusercontent.com/assets/12944354/9354855/3f33d794-46b7-11e5-91a7-369706d9d2ab.png)

**Comment by PatriceTorchet** [comment]
Ok, looks like my mistake
