### ISSUE TITLE
Task select from used part of pane

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#43]
Bug or feature request ?
TDL70
Win 7 pro 64

I am unable to select a task using the right part of attributes pane, after last column.
It is tempting to click there because it will not do anything since it is not a column.

**Comment by abstractspoon** [comment]
It is working correctly and is consistent with Explorer. It works this way so that you can select multiple tasks by dragging a bounding box.

**Comment by TonyGravagno** [comment]
As this is not a bug and not specific to W7 I've removed those labels. That leaves this as a closed feature request.
