### ISSUE TITLE
Unneeded strings in YourLanguage.csv

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Issues#45]
Win 7, x64
TDL 7.0

These strings are not needed in YourLanguage.csv
"Activate embedded or linked object"      ""           "text"
"Change icon of selected object\nChange Icon"  ""           "text"

**Here are the emails**:
Von: daniel.godson@gmail.com [mailto:daniel.godson@gmail.com] Im Auftrag von Daniel Godson
Gesendet: Mittwoch, 19. August 2015 04:01
An: Hotmail
Betreff: Re: Updated translation (Russian)

They ought not to be in the language files, so this represents a bug in my code.

Could you create a simple ticket that will 'force' me to fix this?!

Rgds, .dan.g.

www.abstractspoon.com

On 19 August 2015 at 07:59, Hotmail <nojunk217@hotmail.com> wrote:
Done – uploaded to Github.
 
Dan, please check these strings:
 
NEED_TRANSLATION
"Activate embedded or linked object"      ""           "text"
"Change icon of selected object\nChange Icon"  ""           "text"
 
They appear only in Spanish, Russian and YourLanguage. „Good guys“ (to be added to all others) or „bad guys“ (to be removed)?

**Comment by abstractspoon** [comment]
Fixed in 7.0.1
