### ISSUE TITLE
Global Setting for View

### ISSUE THREAD

**Issue by BradleyShroyer** [abstractspoon/ToDoList_Issues#46]
It would be nice to have a way to set the view for all Tasks based off the current task.

I have the columns I like to see and set their widths for a task (including divider bar position in v7.0.0). Then I have to do it all over again when I open another tasklist. If I change what columns are visible, it works great for new tasklists, but all my old lists do not change.

**Comment by Pierre-de-la-Verre** [comment]
The large dialogue "Attribute Visibility" has on the right lower corner the option "Apply changes to: All tasklists / Current tasklist". This could solve a part of your wish - the visibility (but not the width).

**Comment by abstractspoon** [comment]
Moved to Google Group
