### ISSUE TITLE
-ab/-at switches set fields even if lists locked and values not in list

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#47]
Use switch "-ab foo" in a simple UDT to set the Allocated By field to foo. I didn't expect this would work when the dynamic droplist is set to "Make this list read-only". Same for -at for Allocated To.

~~The Person and AllocatedBy tags are updated with the fields. But as you see AllocatedBy is duplicated.~~

```
<PERSON>foo</PERSON>
<ALLOCATEDBY/>
<ALLOCATEDBY>bar</ALLOCATEDBY>
```

*[EDIT]* It's valid to have an empty ALLOCATEDBY tag. That's not a bug.

**Comment by abstractspoon** [comment]
[Hmmm...](../blob/master/CONTRIBUTING.md)

**Comment by TonyGravagno** [comment]
LOL, well, I can't tell if this is a regression because in 6.9 I believe there was an issue where manual entry was allowed even with the lock on. But to reproduce:

- Set the read-only option for the dynamic lists. Close/re-open TDL to refresh the INI.
- Create a simple UDT with "-ab foo" or "-at foo" as the argument.
- Select a task and click the toolbar icon to execute the UDT.

Corrected original report - it's valid to have an empty ALLOCATEDBY tag. That's not a bug.

**Comment by abstractspoon** [comment]
Thx Tony.

What behaviour are you expecting? The command silently fails or you get notified with a message box (which means translation updates)?

**Comment by TonyGravagno** [comment]
I'm very hesitant to propose anything that implies a translation effort. However a silent failure isn't good either. Please see this forum [thread](http://www.codeproject.com/Messages/5112546/Re-UDT-cmd-nnnnn-Not-working.aspx) from just a moment ago where we're discussion switch validation and errors.

**Comment by abstractspoon** [comment]
Cool. Have responded on CP.

Rgds, .dan.g.

www.abstractspoon.com

**Comment by abstractspoon** [comment]
Just had a thought. Simply disabling the preference is enough to circumvent this. It's not like the tasklist is readonly and it's being changed. And the person running the UDT is necessarily the person who can turn off the preference so is there really any point in writing code to enforce this?

**Comment by TonyGravagno** [comment]
As with any system where data isn't pre-validated, it allows an unexpected entry in the table of valid data. I don't think it's a big deal but the whole point of the read-only switch (to my understanding) would be to keep the fields from gathering dust - like two spellings of a person's name or initials rather than a name, etc. I'm just thinking the protection is there for a reason and we've found a way to get around it. So yes, to tie up the loose ends I don't think it should be possible to "back-door" data in, where the user explicitly says they want the data protected by setting the ini preference.

This applies to the Library too. I haven't yet integrated tasklists with their ini preferences, that's just another back-door. But as it developers I'm going to have to handle the case where a task value is outside the table in the ini when the read-only flag is set. With a flag like ObserveConfigRules, I would have to throw an exception or otherwise indicate to client-side code that an attempt to set a value is invalid.

Thoughts?

(No need to keep re-assigning me to the task during a discussion. I check frequently. Thanks.)

**Comment by abstractspoon** [comment]
>> No need to keep re-assigning me to the task during a discussion

But it helps me keep track of what I need to look at :)

**Comment by abstractspoon** [comment]
Hi Tony. Can you move this to the Google Group as discussed last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support
