### ISSUE TITLE
German Translation does not show "Umlaute"

### ISSUE THREAD

**Issue by molodeztom** [abstractspoon/ToDoList_Issues#48]
The UI shows strange characters instead of German " umlaute" (äüö..). User text is displayed correctly. 
![todolisterror](https://cloud.githubusercontent.com/assets/13887230/9383943/1ba29270-474d-11e5-80ca-88b94f969544.JPG)

Windows 7, Version

**Comment by molodeztom** [comment]
It seems I am not allowed to set labels. 
Version used 7.0.0
Windows 7 German
Bug

**Comment by Pierre-de-la-Verre** [comment]
See discussion here:
http://www.codeproject.com/Messages/5111927/To-the-User-of-German-language-An-die-Nutzer-der-d.aspx

and Github here:
https://github.com/abstractspoon/ToDoList_Issues/issues/39
