### ISSUE TITLE
Permanent "issue" to discuss unneeded / bogus strings in language files (don't close it!)

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Issues#49]
As discussed with Dan - this topic should be discussed and maintained, but bot closed:

20.08.2015: TDL 7.0, Textstrings for the tooltips
>     "File Link:\t"	""	"text"
>     "File Link:\t\t"	""	"text"

It seems that the string with doubled \t is outdated. Correct?

**Comment by TonyGravagno** [comment]
Should have been created under Resources.

**Comment by Pierre-de-la-Verre** [comment]
Move to "Resources":
https://github.com/abstractspoon/ToDoList_Resources/issues/22
