### ISSUE TITLE
TDL 7.0 RC2 - slow starting with multiple files

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#5]
_From @abstractspoon on July 13, 2015 9:1_

_From @Pierre-de-la-Verre on July 10, 2015 17:46_

TDL 7.0 RC2 starts 3-4 times slower than 6.9.6.

See video:
http://autode.sk/1UEKDcK

Data-attachments are not allowed ... :-(

_Copied from original issue: abstractspoon/ToDoList_Resources#6_

_Copied from original issue: abstractspoon/ToDoList_Wiki#7_

**Comment by abstractspoon** [comment]
I'm having no luck at all figuring this out so I'm going to leave it for now.

**Comment by Pierre-de-la-Verre** [comment]
Fixed with TDL 7.0, 15.08.2015
