### ISSUE TITLE
-tid $(userText, var, "Task ID") with wrong behaviour

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Issues#50]
Origin: Codeproject discussion
http://www.codeproject.com/Messages/5112340/Re-please-advise-how-do-you-find-ONE-specific-task.aspx

Reproduced on my PC:
* TDL 7.0
* Win 7 x64, German   

- - - -  
#### Environment: 
* Create a UDT:
> Go to Preferences > User Defined Tools
Click New Tool, enter name "Go To Task".
Set the Path to your ToDoList.exe, like "C:\My Programs\ToDoList\ToDoList.exe"
Set the arguments to this: -tid $(userText, var, "Task ID")
Copy/paste the Path into the Icon field so that your toolbar icon indicates this is executing a ToDoList function.
Click OK to save.

* Use a simple Todolist with eg. 3 tasks (task ID 1 - 3)
* Set Task-ID 2 to "done"
* Set Preferences to "Do not allow a second instance of TDL"

#### Problem 1:
* Use filter "Show: B) Incomplete tasks"
* Use the UDT to search for ID 2 (not displayed) -> a new instance of TDL is started, Filter "Show: A) All tasks" is active an task 2 is displayed  
**Suggestion:**  Display a dialogue: "ID 2 was found, but is not displayed because of your filter settings. Should it be displayed, setting the filter to "Show: A) All tasks"
* Use the UDT to search for ID 99 (not existing) -> a new instance of TDL is started, the same view is displayed as in the first instance.  
**Suggestion:**  Display a dialogue: "ID 99 does not exist."

#### Problem 2 (Side effect):
* Start TDL, create and save a new TDL with the content described above
* Search for not existing ID -> the new instance opens all files of the first instance, but not the new created (maybe it is not written to the INI yet)

**Comment by abstractspoon** [comment]
Excellent report Peter. Can you also add OS and TDL version information to the top pls?

**Comment by abstractspoon** [comment]
ps. Can you suggest how you would want Problem 1 fixed pls?

**Comment by Pierre-de-la-Verre** [comment]
> Can you also add OS and TDL version information to the top pls?  
Do we need both "labels" and "text inside the comemnt"?

**Comment by abstractspoon** [comment]
Yes pls, because I scan the top lines first for that specific information.
That's why we have specified a certain format.

Rgds, .dan.g.

www.abstractspoon.com

**Comment by abstractspoon** [comment]
Many thx for the additional information and suggestions

**Comment by abstractspoon** [comment]
Fixed in 7.0.1.

If the requested task is hidden by the current filter the filter is toggled off. No new messages have been added.

**Comment by Pierre-de-la-Verre** [comment]
Fixed in 7.0.1.

**Comment by TonyGravagno** [comment]
Assigning to myself for wiki update

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#26
