### ISSUE TITLE
Unselect multiple selection 

### ISSUE THREAD

**Issue by andrewculda** [abstractspoon/ToDoList_Issues#51]
OS: Windows 7 Pro
TDL: 7.0

Just upgraded ToDoList to ver.7 and I noticed that when I'm selecting multiple tasks (whether consecutive or not), I cannot unselect that group by selecting a single item from that selected group; instead, i must select a different task that is not part of the selected group. Is that a bug or?
I'm on Win7Pro.

**Comment by TonyGravagno** [comment]
Verified different behavior from v6.9.

**Comment by abstractspoon** [comment]
@andrewculda : Can you confirm the method of selection that you are using and if using the mouse where you are clicking?

**Comment by andrewculda** [comment]
Yes, I'm on a standard PC. I use my mouse and keyboard when selecting the batch. I'm selecting the first item, hold SHIFT and then the last task - for consecutive tasks - or CTRL for non-consecutive tasks.

**Comment by abstractspoon** [comment]
Fixed in 7.0.1

**Comment by TonyGravagno** [comment]
@andrewculda would you like to confirm the fix so this ticket can be closed? Thanks.

**Comment by andrewculda** [comment]
Sure. I upgraded to ver. 7.0.1 and the issue is no longer occurring. I can unselect the group by selecting an item within the selected group.
