### ISSUE TITLE
Unable to complete multiple recurring tasks when 'Recreate Task' is enabled

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#52]
TDL70
All OS

Unable to complete multiple recurring tasks when 'Recreate Task' is enabled

**Comment by abstractspoon** [comment]
This is by design, so I've changed it to a feature request.

**Comment by abstractspoon** [comment]
ps. Please don't put 'All OS' unless **you** have tested all OSes. This is a tag for me to use when I am satisfied it really does affect all OSes

**Comment by PatriceTorchet** [comment]
OK no "All OSes" tag

**Comment by TonyGravagno** [comment]
Dan, please ensure this is in your tasklist as an enhancement so we can close this for the migration to GG.

**Comment by abstractspoon** [comment]
Moved to Google Group
