### ISSUE TITLE
XSL Stylesheet(s) Fail to Display Completed Tasks with Strike-through

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#55]
OS: Windows 7
TDL: 7.0

In 6.9 and before TDL would always export the DONEDATESTRING task attribute so that stylesheets could use this to determine if a task should be shown with strike-through. Unfortunately this also had the side-effect of causing all exporters to display the completion date even if the user did not ask for it.

In 7.0 I attempted to rectify this by storing the DONEDATESTRING as an XML element together with the attribute HIDE="1" so that exporters could skip over the DONEDATESTRING in those cases where the user did not ask for it.

Unfortunately this has broken the stylesheets which rely on DONEDATESTRING always being an attribute.

I can't immediately see an alternative other than changing the stylesheets to accommodate this change but I am open to debate.

STEPS TO REPRODUCE

1. Create a new tasklist with one completed task
2. Ensure the completion date column is **hidden**
3. File > Print Preview
4. Stylesheet: *Z_SimpleReport.xsl*
5. Attributes > Visible Columns Only
6. OK

Observe that the task is displayed **without strike-through**.

7. Now ensure the completion date column is **showing**
8. Repeat 3-6

Observe that the task is now displayed **with strike-through**.

This is an example task with a hidden completion date (and ID):

```<TASK TITLE="HELLO WORLD" ...>
<ID HIDE="1">2</ID>
<DONEDATE HIDE="1">42242.32778935</DONEDATE>
<DONEDATESTRING HIDE="1">26/08/2015 7:52 AM</DONEDATESTRING>
</TASK>```

**Comment by TonyGravagno** [comment]
I must be missing the problem: This code is from one of the stylesheets, to display the correct style if the attribute is present:
```
  <xsl:choose>
	<xsl:when test="@DONEDATESTRING">
	  <xsl:attribute name="class">masterCompletedTaskTitleText</xsl:attribute>
	</xsl:when>
	<xsl:otherwise>
	  <xsl:attribute name="class">masterTaskTitleText</xsl:attribute>
	</xsl:otherwise>
  </xsl:choose>
```
In the above case, if the DONEDATESTRING is always present, then a further check is required to see if it has a non-null value:
```
<xsl:if test="@DONEDATESTRING !=''">
```
With "proper use" of XSL, any report can visually indicate the correct status of a task. If someone is generating a transform and not including that data element, they should, unless a new mechanism is defined to always be present for testing the completion status.

**Comment by abstractspoon** [comment]
Interestingly, neither of your stylesheets seem to display strikethrough under any conditions...

**Comment by TonyGravagno** [comment]
I'll do some more testing but I'm sure that my results won't be different from yours. That said, when the original report was posted to the forum I tested to verify and I did get strike-through in both preview and the HTML file.

**Comment by abstractspoon** [comment]
```<xsl:when test="@DONEDATESTRING">```

This the problem line I think. I believe that that '@' instructs MSXML to look for an **inline attribute**. The code needs to be modified to also check for a **child element** having this name. 

Unfortunately I've no idea what needs to be added to handle this. I've emailed zajchap separately which is why this is allocated to him.

**Comment by TonyGravagno** [comment]
I see. The syntax for that would be:
```<xsl:if test="child::DONEDATESTRING">``` or ```<xsl:when test="child::DONEDATESTRING">```
with subsequent testing for ```@HIDE```.

If you put DONEDATESTRING back as an attribute **and** leave it as an element, I believe it will be usable by existing stylesheets again as well as serving the new purpose - the addition of the new element shouldn't break existing code.

**Comment by TonyGravagno** [comment]
Dangit, I can't assign more than one Assignee, sorry.

**Comment by abstractspoon** [comment]
Leaving DONEDATESTRING as an attribute would completely defeat the purpose, as everyone could just leave their stylesheets unchanged!

**Comment by TonyGravagno** [comment]
I don't like this but it addresses the problem without breaking legacy reports:

- A new update sets a new INI preference IncludeDoneDateInTransform. I recommend a value of 1 to allow v6.9-compliant transforms.
- Another new preference is added, IncludeDoneDateInExport. This should default to 0. 
- The transform and export check that flag to decide if the attribute is included or not. No need for a new XML element or attribute.

What I don't like about that is that it requires a mod to the preference screen and an update of the INI. That's extra work for you. Another mod that's probably necessary is a checkbox on the export and transform dialogs : Include DoneDateString. Then this can be toggled on a per-report basis to override the global preference.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Wiki#28
