### ISSUE TITLE
Text unreadable in update changelog/progress window with HighContrast theme

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#57]
TDL v7.0, Windows (unknown which version)

"Couldn't read anything while updating in the changelog/progress window due to #HighContrast theme."

Original report [here](https://twitter.com/Martin0815/status/633217349068435456). Discussion [here](http://www.codeproject.com/Messages/5116939/App-Update-progress-unreadable-with-HighContrast-t.aspx).

Dan confirmed ability to reproduce issue. Will fix for 7.0.2.

**Comment by abstractspoon** [comment]
Fixed in 7.0.2.
