### ISSUE TITLE
Request: Shortcuts for custom string

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#59]
_From @astrakid on August 31, 2015 12:35_

Hi,
I would appreciate to have some shortcuts for entering standard text. e.g. I am using shortcut for entering current date, but it would be great to have some further information added here (my "shortcode" cor commenting tasks).

_Copied from original issue: abstractspoon/ToDoList_Resources#23_

**Comment by abstractspoon** [comment]
_From @Pierre-de-la-Verre on August 31, 2015 13:0_

I would recommend Third-party for this:
- Autohotkey AHK http://ahkscript.org/ for this. You can use it for "Shortcut Oneliner Code" up to complex programs. 
- Fast Typing: https://sites.google.com/site/ultratceditors/fast_typing
and many more ..

**Comment by abstractspoon** [comment]
_From @astrakid on August 31, 2015 13:22_

Thanks for the hints, I understnad the way, but would have liked it to have an "embedded solution". Time and Date could also be managed via ahkscript, but is implemented in todolist.
thanks for your comment,
regards,
astrakid

**Comment by abstractspoon** [comment]
@astrakid : Can you be more specific about the solution you are seeking
together with some clear examples of what you want?

Rgds, .dan.g.

www.abstractspoon.com

**Comment by abstractspoon** [comment]
_From @astrakid on August 31, 2015 14:11_

sure. I would like to have a shortcut for inserting the date and a custom text, e.g.:
STRG + D => [date] + "comment akid: "
I want to use your existing shortcut and add a custom string. If it is not possible to mix it up it would be a step into the right direction to have another shortcut for custom string, e.g. STRG+E => "comment akid: ", in this case I would need to press STRG+D and STRG+E sequentially to get my desired result. ;-)
regards
astrakid

**Comment by abstractspoon** [comment]
_From @astrakid on August 31, 2015 14:12_

Just saw, that CTRL+D is timestamp, not date. nevertheless, doesn't matter which shortcut is used...
and "STRG" is "CTRL"... ;-)

**Comment by abstractspoon** [comment]
_From @TonyGravagno on September 1, 2015 18:9_

I use [PhraseExpress](http://www.phraseexpress.com/) for this. Have used it for many years. It works in all apps, wherever you're typing anything. It's extremely powerful and it's free for personal use. No programming required though you can create macros for dynamic text.

(IMO) ToDoList doesn't need this built-in when there are a number of free and awesome tools that do so much more than TDL ever could. If you want to start a separate discussion about this in the [TDL Google Group](http://bit.ly/AbstrToDoListGG), I'll be happy to discuss it there.

**Comment by TonyGravagno** [comment]
@astrakid It looks like for now you just want to follow the time stamp with the user name. That's already built-in. In Preferences > User Interface > Tasklist Attributes, under Date/Tim Formatting:

[x] Append the user's 'Created By' name when pasting the 'Date/Time'
[x] Append the following text when pasting the 'Date/Time'

**Comment by astrakid** [comment]
That is a Great hint which i will try tomorrow! Thanks a lot!

Regards
Andre

Sent from my mobile C64

**Comment by astrakid** [comment]
perfect!!! that is exactly the solution i was looking for! thanks a lot.




Von:    Tony Gravagno <notifications@github.com>
An:     abstractspoon/ToDoList_Issues <ToDoList_Issues@noreply.github.com>
Kopie:  Andre G <andre.gronwald@gfi.ihk.de>
Datum:  02.09.2015 21:19
Betreff:        Re: [ToDoList_Issues] Request: Shortcuts for custom string 
(#59)



@astrakid It looks like for now you just want to follow the time stamp 
with the user name. That's already built-in. In Preferences > User 
Interface > Tasklist Attributes, under Date/Tim Formatting:
[x] Append the user's 'Created By' name when pasting the 'Date/Time'
[x] Append the following text when pasting the 'Date/Time'

**Comment by TonyGravagno** [comment]
This ticket can be closed for the OP but the concept of the request is still valid. He wants to hot-key in common phrases, and he may not be able to use other apps because (described [here](https://groups.google.com/d/msg/abstractspoon-todolist-support/FPaS4pjuinw/Cwd8PwjmBAAJ)) he's running ToDoList as a portable app. This phrase happens to be (made up code here) ```$(username)```. But it's not unreasonable to consider other phrases assigned to hotkeys, like "Test for the next release" or "Management decided this was not necessary".

I don't have a want/need for this myself but if this closed now then others won't have a chance to +1 the idea later. So I suggest it remains open as an "Idea".

**Comment by abstractspoon** [comment]
@TonyGravagno : As you pointed out this is a classic case of excellent 3rd-party solutions already existing so I can safely say that this would be unlikely to ever get into TDL
