### ISSUE TITLE
TDL 7.0 RC2 - Deleting last filelink is no more possible

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#6]
_From @abstractspoon on July 13, 2015 9:1_

_From @Pierre-de-la-Verre on July 10, 2015 17:48_

Deleting last filelink is no more possible - see video:
http://autode.sk/1LYjMFx[^]

_Copied from original issue: abstractspoon/ToDoList_Resources#7_

_Copied from original issue: abstractspoon/ToDoList_Wiki#6_

**Comment by abstractspoon** [comment]
Fixed in RC3. Can you confirm and close.

**Comment by Pierre-de-la-Verre** [comment]
Semi solved. The deletion of file-links has to be confirmed via "Enter"; otherwise it is not removed.

Video: http://autode.sk/1Ieci0C

**Comment by abstractspoon** [comment]
It would also help me if you told me what you think the correct behaviour should be.

eg. After deleting an item, the file ref field is empty. What do you think it should show?

**Comment by Pierre-de-la-Verre** [comment]
Hi Dan

 

I could be like this:

 

Idea 1:

- click the “List-Button” – list appears (Done)

- click an “Erase Icon” 

               a) link should be really erased 

               b) reduced list should be displayed

               c) first entry in the list should displayed in the field and its icon in the column

- moving the mouse to somewhere should finish this action (like it is when deleting the last value of the list)

 

Idea 2:

Another option (maybe complicated):

- create the list with a multiple-selection

- make a command (button ( icon) to delete all selected link at once

 

Idea 3:

Same as Idea 1, but in step c) a temporarily string like “File test.dll was erased” is dispalyed

 

Peter

 

Von: .dan.g. [mailto:notifications@github.com] 
Gesendet: Montag, 20. Juli 2015 13:47
An: abstractspoon/ToDoList_Issues
Cc: Pierre-de-la-Verre
Betreff: Re: [ToDoList_Issues] TDL 7.0 RC2 - Deleting last filelink is no more possible (#6)

 

It would also help me if you told me what you think the correct behaviour should be.

eg. After deleting an item, the file ref field is empty. What do you think it should show?

**Comment by abstractspoon** [comment]
Thx Peter. Idea 1 feels like the most intuitive.

**Comment by abstractspoon** [comment]
Hi Peter, this should be fixed properly in the 'new' RC3

**Comment by Pierre-de-la-Verre** [comment]
Confirmed - fixed properly in the 'new' RC3.
