### ISSUE TITLE
General comment about the whole project

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#61]
_From @Stoffe on September 2, 2015 8:27_

There is a possibility to add a comment on tasks and categories.
However Im missing the possibility to add a general comment about the whole project.
Like, describing the project or to make a comment that all who opens this project will read.
There is the small line on top to describe your project, but sometimes you need to write more than that. :/

_Copied from original issue: abstractspoon/ToDoList_Wiki#24_

**Comment by TonyGravagno** [comment]
I'd expand on this and suggest that custom attributes for tasks could be applied to a project. So an entire tasklist could have a start date, a due date, comments, cost, and version.

That said, @Stoffe, we use the first top level task for this kind of thing. Why is that inadequate?

See Issue #40 where a similar concept is described. In the wiki there is an example of tasks being used as [containers](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Defining-Tasks).

**Comment by abstractspoon** [comment]
Moved to Google Group
