### ISSUE TITLE
Service or API that you can read this file format from

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Issues#62]
_From @Stoffe on September 2, 2015 8:26_

A possible extra feature is an service or API possibility to read this fileformat and do things of your own with it, for instance, read it and display the projects and their status on a webserver.

_Copied from original issue: abstractspoon/ToDoList_Wiki#23_

**Comment by TonyGravagno** [comment]
That's the definition of the [ToDoListLib .NET](https://todolistlibdotnet.codeplex.com/wikipage?title=Applications) which I still need to publish.

**Comment by abstractspoon** [comment]
Hi Tony. Can you move this to the Google Group or close it as required? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support

**Comment by TonyGravagno** [comment]
https://groups.google.com/d/msg/abstractspoon-todolist-support/yJrAlUIEErA/0mCAz0xcAQAJ
