### ISSUE TITLE
Icons missing in UI - TDL 7.0.1, Linux

### ISSUE THREAD

**Issue by Simplenuity** [abstractspoon/ToDoList_Issues#64]
Three icons in the UI are missing. 
To reproduce start TDL from scratch with the 'Introduction' tasklist.
![sample tasklist - todolist c abstractspoon_007](https://cloud.githubusercontent.com/assets/13347943/9627876/455b27d0-51bb-11e5-82c6-8949dfc927d6.png)

**Comment by abstractspoon** [comment]
Yes, these are part of the ```Wingdings``` font that perhaps does not exist on Linux...

**Comment by Simplenuity** [comment]
I can see wingdings installed in Wine. 
Are there any of the successfully displayed icons deriving from wingdings? Am asking to understand whether it's rather a difference in wingdings fonts used or a general problem. Unfortunately MS has changed the license on wingdings some time ago, so it's obviously not free anymore.
Will look into it further...

**Comment by abstractspoon** [comment]
I solved this by copying wingdings.ttf from Windows7 to /home/dan/.fonts/wingding.ttf and then restarting TDL

**Comment by Simplenuity** [comment]
Thanks Dan, I also started looking into it yesterday, did some (successful) tests with a windings version I found here on GitHub. Also I'm currently testing font viewers. Will get back to you when I have a satisfying solution.

**Comment by Simplenuity** [comment]
Update:

1- Difference between the two wingdings versions:

- installed by wine: /usr/share/wine/fonts/wingding.ttf
![winewingdings wingding ttf mac _010](https://cloud.githubusercontent.com/assets/13347943/9702048/88cdf762-54a0-11e5-9b27-83c03f0e488e.png)

- manually installed version:
https://github.com/caarlos0/msfonts/blob/master/fonts/wingding.ttf
![wingdings-regular wingding ttf mac _011](https://cloud.githubusercontent.com/assets/13347943/9702072/f3555c78-54a1-11e5-9b53-2766bff9da2d.png)

Wingdings provided by Wine is unfortunately very limited. I can't see decent replacement icons in there. The manually installed version might be a solution, but the license needs to be clarified before publishing it on the Wiki/ in the readme file.

2- Font viewer
You can install one (that actually shows the symbols) by doing these steps:
a- open a Terminal
b- run:
```  
sudo apt-get install fontmatrix
``` 
Fontmatrix is more than a font viewer, but the simple font viewer doesn't show the symbols correctly.

**Comment by Simplenuity** [comment]
moved over to GoogleGroups
