### ISSUE TITLE
Allow suppression of dialogs from command-line actions

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#68]
Some command-line switches can cause ToDoList to open a dialog to prompt the user for verification. This can interrupt automation. For example, use the -cd switch to set the completed date on a task. If the task has a child task which is not complete, a yes/no dialog opens.

This enhancement request is to add a switch or other code which can be used to preclude such dialogs. The default however will preserve the current behaviour.

Examples:
```todolist -tid 1 -cd "1/1/2015" -d_cd n``` ... Dialog for Completion Date value is No
```todolist -tid 1 -cd "1/1/2015" -d_dd y``` ... Dialog for Due Date value is Yes
or

```todolist -tid 1 -cd "n~1/1/2015"``` ... Parse dialog response from value
```todolist -tid 1 -cd "y~1/1/2015"```

There could be a single -nd for No Dialog switch, but then how are values overridden if the default is not preferable?

**Comment by abstractspoon** [comment]
As discussed, I've no plans to support this in the foreseeable future.
