### ISSUE TITLE
Command-line switches with Units

### ISSUE THREAD

**Issue by TonyGravagno** [abstractspoon/ToDoList_Issues#70]
The command-line switches for Time Estimate and Time Spent (-te and -ts) reset the field value to Hours as they set the value. I believe that's a bug.

There is no provision for setting the units from a switch. For completeness, not my immediate need, I'm hoping units can be added to that as well - something like this which combines elements from a couple code modules:

```
if (cmdInfo.GetOption(SWITCH_TASKTIMEEST, sValue))
{
   TCHAR nUnits = GetTimeUnits(sValue, 0);
   if (nUnits)
      dTimeEstUnits = nUnits;
   else {  // if not, leave units at current setting }
   dTimeEst = _ttof(sValue);
}
```

**Comment by abstractspoon** [comment]
Sounds like a good idea. For now I'll correct the current behaviour not to change the existing units.

**Comment by abstractspoon** [comment]
Hi Tony. Can you move this to the Google Group as discussed last week? Thx

https://groups.google.com/forum/#!categories/abstractspoon-todolist-support

**Comment by TonyGravagno** [comment]
Done
