### ISSUE TITLE
TDL702 not honoring option in print/transform

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#71]
Bug in TDL 702, win7 pro 64.
I spotted the bug in Preview and Tool>Transform, I guess others are affected.
For Selected tasks only, the sub option Include parent tasks is not honoured.
The parent tasks are not included in the intermediate file.

Feature request
It would be nice to have the include parent tasks with the filtered tasks choice.

**Comment by abstractspoon** [comment]
Thx Patrice. Can you move this to the Google Group as per my email last week? Thx

(https://groups.google.com/forum/#!categories/abstractspoon-todolist-support)

**Comment by abstractspoon** [comment]
Moved to Google Group
