### ISSUE TITLE
TDL702 Setting { Display a task's 'Due Date' as: 'Its assigned date' } not saved

### ISSUE THREAD

**Issue by G-Eric** [abstractspoon/ToDoList_Issues#72]
Windows 7  //  TDL v7.02

**Preferences > Tasks > Attribute Calculations > Display a task's 'Due Date' as:**

For this setting, it is not possible to activate the last offered value (named 'Its assigned date').
When you select it, click on <ok> button (to save the setting) and then return into Preferences to check if it was recorded... it's not: *the 1st offered value (labelled 'the earliest...') is selected instead.*

I suspected it might be "explained" by / in link with another date related setting, but...
- after many trial & tests (toggle settings), I did not find any relation: this option remains impossible to be selected (saved) / activated
- I also guess that this value would have been greyed if it was not acceptable in relation with a specific combinaison of other settings; and therefore, if it is available, it is an acceptable setting that might be selected / activated.

**Comment by abstractspoon** [comment]
Moved to Google Group
