### ISSUE TITLE
TDL 702 Displayed records in tab "Task Tree" and "List View"  >>  sort not ok

### ISSUE THREAD

**Issue by G-Eric** [abstractspoon/ToDoList_Issues#73]
Windows 7  //  TDL v7.02

**_Displayed records in tab "Task Tree" and "List View"  >>  sort not ok_**

*_Remark_*
I do not use the same "sort" setting in both views:
- tab "TaskTree" is sorted by title
- tab "List View" is sorted by due date then by title

When switching bewteen these 2 tabs (from one tab to the other, whatever the "from" and the "to" are), I need to have the display manually forced refreshed (F5 for me) to get properly displayed list (i.e. according to sorting criteria for this specific view).
Otherwise, by default, the "to" tab (i.e. the one to which I did went to) is sorted with the sort criteria defined for the "from" tab (i.e. the one in which I was).

I would expect that a click on the another tab (= to have the view of this tab activated as the active display) would force a refresh of the contents just before displaying it.
According to my tests, this is not the case (i.e. if it is programmed like this, the result is not what it is expected)

So, to document my explanantion:
- I start in the tab "Task Tree": my records are displayed sorted by "title"
- I click on the tab header "List View" to switch to this view
- the tab is activated, and the list is displayed sorted by "title" (i.e. instead of 'due date' > it is 'title') = not ok
- I press F5 to force the display refresh
- the list is now displayed according the the sort criteria of this tab (i.e. change from 'due date' > 'title') = ok
( i )  My expectation is to have the list displayed "by due date > by title" immediately when entering the tab "List View"

**Comment by abstractspoon** [comment]
Moved to Googe group
